# Section 0: Lab structure and expectations

Welcome to your MTH343 applied linear algebra code notebook! This notebook contains background information, class exercises, and homework assignments for the term. In the exercise and homework sections, there are comments specifying where you are expected to fill in the code to complete the activity.

My name is Austen and I'm the TA for the class and author of this notebook.

*   email - ajn6@pdx.edu
*   office - 460E
*   discord - if there is a student made class discord you want me to join then let me know and I will. I will probably notice email first for help privately but it can be helpful to other students if you're willing to ask for help publicly


## Notebook Structure

Much of the notebook is explanation and examples. I encourage you to interact with and change the code I have written in these sections. Throughout the notebook you will be expected to add code and text responses in exercise, homework, and final project sections. Sometimes I have completed part of the code and you just need to fill in the missing part. Any places you need to add code should contain a comment like:

```python3
# Your code here
```

__Exercise sections__ should ideally be completed in the provided class working time or in office hours with me (Austen the TA). You are encouraged to work together on these exercises. Grading will be completion based and there is no expectation that your code be any different from other class members. There are exercises for each of the 6 sections of content, some more involved than others.

__Homework sections__ can be worked on in class but try to do most of it on your own. Discussing solutions and algorithms or helping each other debug code is encouraged but please try not copy other student's solutions for these sections. There are 4 homework found in sections 1, 2, 3 and 4. There are no due dates for the individual homework but you will be expected to check in your work in the lab book at the time of the midterm. The lab notebooks will be due the Friday of finals week.

The __Final Project__ section is an application of multiple topics from throughout the term. This is the largest code you will write and preferably getting help with your code on this project will happen in office hours or through email or discord correspondence with me. It should be implemented as part of this notebook at the end and is due with the rest of the notebook on the Friday of finals week.



## Office hours and notebook progress

I have a class starting 30 minutes into this meeting time so our tentative plan is to spend this time in lecture working on this notebook. I will be holding office hours for the hour before class (4:00-4:40 M/W LH 249) where I will be available to answer questions and help with code.

I understand there are many of you with limited python experience and this class will be a lot of new information, so utilizing office hours and in-class work time is important. If the scheduled times don't work I am on campus often, feel free to schedule a meeting time or just come see if my office door is open.



## Combining the theory with practice

This notebook is far from complete. It is expected you use notes and algorithms presented in class when completing the activities. The activities generally follow the topics you will be covering in lecture but that doesn't mean you can't work ahead for a challenge.

## Expected Background Knowledge

I'm assuming that everyone is comfortable with conceptual programming topics like variables, basic types (i.e. int, float, string), control flow (i.e. loops, if-else), and functions. If this isn't the case we might need to step back and review these in the first week of class.

It would also be helpful but not critical to have an idea of objects and classes and have some experience using them. We will be heavily interacting with the `numpy.ndarray` and `scipy.sparse.csr_array` classes but we shouldn't need to declare or create any classes of our own.

Knowledge of different common Python data-structures like lists, tuples, dicts (maps), and sets will be helpful but a simple examples of their usage is provided when introduced.

## Recipe For Success

There are a couple of suggestions I can give for suceeding when learning to code or learning new languages.

The first is applicable to most learning, code in shorter intervals more often. Coding or studying for 30 minutes a day is better than coding all day once a week. Notice that this suggestion requires you start the homework before the due date... When you keep the material in your subconscious you will solve problems and have breakthroughs at the strangest times. I've solved some of the most difficult problems I have worked on when waking up in the middle of the night, but I rarely solve something if I have been working on it the last 6 hours.

The second is to get help if you are stuck or convinced that your code is correct. 'Rubber duck debugging' is very real and explaining your code to someone else often breaks the functional fixedness that is hiding something in plain sight. It is expected that you will require help to get through this class and notebook. A small part of class time is dedicated to this but email and office hours will also be key tools you are expected to utilize. If the office hour times do not work for your schedule make sure to schedule some!

# Section 1: Introduction to `colab`, `numpy` and `scipy`

## Google Colab

Google Colab is part of the Goolge Workspace that is pretty much a Google Docs for code. Colab essentially sets up a virtual machine with a development environment with batteries included. The paid version of Colab can give you to more CPU, memory, and even GPU resources if you would like to run computationally demanding codes.

Because Colab is a cloud based service, you will have to be connected to the internet to edit and run notebooks.

The tool that Colab is built on top of is called Jupyter Notebook. Jupyter is a widely used interactive notebook that provides a modular system for editing, documenting and running code. Jupyter is a commonly used tool in the data science industry, primarily because it is nice for documenting and collaborating.

Jupyter has a full markdown integration in the text blocks as well as a powerful `latex` (pronounced 'lah-tek or lay-tek') integration. In this notebook you will see me use `latex` commands such as:

$ Ax = b \quad x,b \in \mathbb{R}^n \quad A \in \mathbb{R}^{nxn}$

As noted in the next section I am not requiring you use Colab. I know that if you are more familiar and configured with another editor or IDE that you would prefer to use that. Colab greatly simplifies the setup and boilerplate required for getting started in this class, though.

### But Jupyter is Trash

I know, I also much prefer using other editors to Jupyter notebooks. When coding examples in class or office hours I probably wont use Jupyter or Colab because I'm a pretentious `vim` purest.

I'm not requiring you use this notebook at all if you would like to use an editor or IDE of choice.

If you want help setting up a development environment I can assist with that, but if you turn in your exercises and homework in `.py` format I will expect a `requirements.txt` so I can quickly create a virtual environment for your work.

Create a separate file for each exercise section, homework, and final project each with a main function that runs all the code for the activity and the
```python3
if __name__ == "__main__":
  main()
```
block included at the bottom of each file. The outputs to the terminal and plots produced by the running the main function should describe the findings and results from the activity.

Lastly, when turning in all these files please put each `.py` and the `requirements.txt` into a folder and archive it like:

 `<name>_mth343-activities.tar`.

If you decide to use the notebook, submitting the link to the shared notebook is fine.

## `numpy` and `scipy`

These are the primary software libraries we will be using throughout the term. It isn't expected you have any experience with these libraries and I try to provide examples of how to use the application programming interface (API) before you are expected to use it yourself. The only way to learn how to use an API is to practice regularly.

Using `numpy` and `scipy` we can do a lot. Matrix multiplication, transpose, inverse, decomposition, and much more are available.

Check out the getting started guides for a lengthy introduction and get used to utilizing the API reference to learn how to use new functions:

`numpy`: [getting started guide](https://numpy.org/doc/stable/user/absolute_beginners.html) and [API reference](https://numpy.org/doc/stable/reference/index.html#reference)

`scipy`: [getting started guide](https://docs.scipy.org/doc/scipy/getting_started.html#getting-started-ref) and [API reference](https://docs.scipy.org/doc/scipy/reference/)

For the first couple weeks of activities we will be using these libraries mostly to check that our code is correct. Later in the term (week 3) feel free to use the library routines unless it is the direct routine you are implementing (ie. if the assignment is to implement `GMRES` don't use `scipy`'s `GMRES` function).

These libraries are widely used and very mature. In the code examples below, I show some basic usage of the utilities provided but I have hardly scratched the surface. Reading the docs, guides/tutorials, and other developer's code on github are great ways to learn new tricks.

## Visualization

Data visualization is an important part of data exploration and analysis and will be a small part of this course. We will mostly use `matplotlib` for simple plotting but I will provide some `plotly` code when we would like to have an interactive 3d plot. For one of the homework and the final project you are asked to plot something similar to what is shown in the examples.

## Loading data into `colab`

One of the first things we will need to do is load data into our code from external files. Matrix data comes in many different forms depending on the source and structure of the matrix.

Start by adding the [shared data folder](https://drive.google.com/drive/folders/1b7jMz1UZ9L5FZPvN_ZG5Hw96bHRCzkht?usp=sharing) to your google drive:

If you don't want to connect Colab to your drive you can upload the files directly into the colab runtime each session. Be careful you trust a notebook before connecting it to your drive, you can read through the code here and see I'm not deleting or downloading your entire Drive.

In [ ]:
from google.colab import drive

drive.mount('/content/drive')
# NOTE: change this to the folder in your drive with the data
folder = 'drive/MyDrive/MTH343/matrices'

Mounted at /content/drive


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Once the folder is loaded we can use `scipy` to load matrix market format files. This format is used to store sparse and dense matrices, `scipy` will return the type of object encoded in the file.

In [ ]:
from scipy.io import mmread

# here I use a format string or f-string denoted by the f'<string>{<eval>}'
matrix = mmread(f'{folder}/bcsstk02.mtx')
type(matrix)

scipy.sparse.coo.coo_matrix

Here we can see that `scipy` loaded a sparse matrix in `coo` format, more about that later.

Another common practice for serializing and deserializing python objects is using the `pickle` module. `numpy` uses `pickle` in its built in save and load functions.

In [ ]:
import numpy as np

matrix = np.load(f'{folder}/100_orthonormal.npy')
type(matrix)

numpy.ndarray

## Matrix and Vector generation

In [ ]:
# we can also generate random matrices with numpy
matrix = np.random.rand(5, 5)
print(matrix)
print(f'The shape of the matrix is: {matrix.shape}\n')

# take note of how these three are subtly different,
# both will behave in very different ways.
# we will explore reshaping in the next section
vector1 = np.random.rand(5, 1)     # column vector
vector2 = np.random.rand(5)        # 'true' vector
vector3 = np.random.rand(1, 5)     # row vector
print(vector1)
print(f'The shape of the vector1 is: {vector1.shape} with {vector1.ndim} dimension \n')
print(vector2)
print(f'The shape of the vector2 is: {vector2.shape} with {vector2.ndim} dimension \n')
print(vector3)
print(f'The shape of the vector3 is: {vector3.shape} with {vector3.ndim} dimension \n')

# other useful generation functions:
ones = np.ones((2, 2))
print(ones)
print('ones\n')
zeros = np.zeros((4,3))
print(zeros)
print('zeros\n')
sequence = np.arange(12)
print(sequence)
print('sequence\n')
eye = np.eye(5)
print(eye)
print('eye\n')

[[0.58397433 0.03054546 0.33767534 0.01210203 0.97263786]
 [0.36633851 0.63604215 0.50475716 0.78898634 0.10491808]
 [0.88204275 0.62693786 0.85623631 0.78235739 0.72559565]
 [0.03083492 0.71529448 0.46708278 0.185656   0.96061919]
 [0.77843471 0.21568669 0.30660083 0.50376684 0.27619591]]
The shape of the matrix is: (5, 5)

[[0.22263263]
 [0.81737964]
 [0.05589469]
 [0.26265203]
 [0.09891202]]
The shape of the vector1 is: (5, 1) with 2 dimension 

[0.24856341 0.7963721  0.44269583 0.4631577  0.08644547]
The shape of the vector2 is: (5,) with 1 dimension 

[[0.74983395 0.14413032 0.73333155 0.869611   0.30126199]]
The shape of the vector3 is: (1, 5) with 2 dimension 

[[1. 1.]
 [1. 1.]]
ones

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
zeros

[ 0  1  2  3  4  5  6  7  8  9 10 11]
sequence

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
eye



## Basic Linear Algebra Routines and Array Manipulation


In [ ]:
matrix = np.random.rand(3, 3)
vector = np.random.rand(3)

# transpose a matrix three ways
print('original:')
print(matrix)
print('option 1:')
print(matrix.T)
print('option 2:')
print(np.transpose(matrix))
print('option 3:')
print(matrix.transpose())

# we can take the product of two numpy arrays in two ways
product_1 = matrix @ vector
product_2 = matrix.dot(vector)
zeros = product_1 - product_2
print('\nshould be zeros:')
print(zeros)

# reshape and concat the two equivelent results
concat = np.concatenate((product_1.reshape((3,1)), product_2.reshape((3,1))), axis=1)
print(concat)
print(f'The shape of concat is: {concat.shape}\n')
# instead of reshape then concat we could use `stack`
stack = np.stack([product_1, product_2])
print(stack)
print(f'The shape of stack is: {stack.shape}\n')
stack = np.stack([product_1, product_2], axis=-1)
print(stack)
print(f'The shape of stack with axis=-1 is: {stack.shape}\n')

# notice that the * operator is not matrix multiplication...
# if the shapes of the left and right side are the same,
# then * does a strictly element-wise multiplicaton
product = product_1 * product_2
print('squared product:')
print(product)

original:
[[0.17157216 0.56214939 0.83046665]
 [0.52802168 0.00515052 0.05698724]
 [0.24654588 0.82048872 0.4730209 ]]
option 1:
[[0.17157216 0.52802168 0.24654588]
 [0.56214939 0.00515052 0.82048872]
 [0.83046665 0.05698724 0.4730209 ]]
option 2:
[[0.17157216 0.52802168 0.24654588]
 [0.56214939 0.00515052 0.82048872]
 [0.83046665 0.05698724 0.4730209 ]]
option 3:
[[0.17157216 0.52802168 0.24654588]
 [0.56214939 0.00515052 0.82048872]
 [0.83046665 0.05698724 0.4730209 ]]

should be zeros:
[0. 0. 0.]
[[1.03124514 1.03124514]
 [0.17833465 0.17833465]
 [1.03353654 1.03353654]]
The shape of concat is: (3, 2)

[[1.03124514 0.17833465 1.03353654]
 [1.03124514 0.17833465 1.03353654]]
The shape of stack is: (2, 3)

[[1.03124514 1.03124514]
 [0.17833465 0.17833465]
 [1.03353654 1.03353654]]
The shape of stack with axis=-1 is: (3, 2)

squared product:
[1.06346653 0.03180325 1.06819779]


### A note about shapes and broadcasting

If the shapes don't match like in the block below, [(3,3) * (3,)], `numpy` recognizes that the first dimension matches and broadcasts the product across the other dimensions.

This is extremely powerful but is also the cause of many headaches for new users
of numpy. Often the code runs and does something different because of the 
implicit broadcast, where you would have wanted it to crash for a dimension
mismatch. Checking the dimensions of your arrays is a solid first step to debugging your `numpy` codes.

In [ ]:
broadcast = matrix * vector
print('Broadcasted elementwise multiplication:')
print(broadcast)

Broadcasted elementwise multiplication:
[[0.04479383 0.4576564  0.5287949 ]
 [0.13785521 0.00419314 0.0362863 ]
 [0.06436788 0.66797531 0.30119336]]


## Slicing and Indexing

One of the most common manipulations on `numpy` arrays is slicing. Slicing allows you to access a portion of the array.

In [ ]:
matrix = np.random.rand(3, 3)
print('original matrix:')
print(matrix)
print()

print('the first column:')
print(matrix[:,1])

print('\nthe first two rows:')
print(matrix[:2, :])

print(f'\nthe element in the bottom right corner: {matrix[-1,-1]}')
print(f'\nthe middle element: {matrix[1,1]}')

original matrix:
[[0.9263837  0.56588814 0.18170419]
 [0.8985681  0.24144046 0.12469358]
 [0.35138521 0.24367984 0.46135569]]

the first column:
[0.56588814 0.24144046 0.24367984]

the first two rows:
[[0.9263837  0.56588814 0.18170419]
 [0.8985681  0.24144046 0.12469358]]

the element in the bottom right corner: 0.4613556921171913

the middle element: 0.2414404567236449


## Filtering, Sorting, and Permuting Arrays

Throughout this notebook you will be required to filter a `numpy` array based on some condition. The beginner way to do this would be to loop through the elements and copy the ones that satisfy the predicate into a new array.

There is a simpler way to filter by indexing an array with another array.

In [ ]:
vector = np.arange(5)
print(vector)

# create mask array with booleans from condition
filter_evens = vector % 2 == 0
print('evens mask:')
print(filter_evens)
filter_small = vector < 3
print('\nless than 3 mask:')
print(filter_small)

# filter the original array with the mask
evens = vector[filter_evens]
print('\nevens:')
print(evens)
small = vector[filter_small]
print('\nless than 3:')
print(small)

# this technique can be use to permute and select certain indices as well
select = np.array([1, 3, 4])
permute = np.array([3, 2, 4, 1, 0])

print('\nselect some:')
print(vector[select])
print('\npermuted:')
print(vector[permute])

# can use in higher dimensions also
mat = np.random.rand(4, 4)
column_swap = np.array([2, 1, 0, 3])
print('\noriginal:')
print(mat)
print('\nwith swapped columns:')
print(mat[:,column_swap])

# simple sorthing is easy
vector = np.random.rand(6)
sorted = np.sort(vector)
print('\noriginal:')
print(vector)
print('\nsorted:')
print(sorted)

[0 1 2 3 4]
evens mask:
[ True False  True False  True]

less than 3 mask:
[ True  True  True False False]

evens:
[0 2 4]

less than 3:
[0 1 2]

select some:
[1 3 4]

permuted:
[3 2 4 1 0]

original:
[[0.30734004 0.34151461 0.23370973 0.27490951]
 [0.83839256 0.23999405 0.26544212 0.67255686]
 [0.37769502 0.21205643 0.76538371 0.93020272]
 [0.57284119 0.37268785 0.10336464 0.89657409]]

with swapped columns:
[[0.23370973 0.34151461 0.30734004 0.27490951]
 [0.26544212 0.23999405 0.83839256 0.67255686]
 [0.76538371 0.21205643 0.37769502 0.93020272]
 [0.10336464 0.37268785 0.57284119 0.89657409]]

original:
[0.83632996 0.64587158 0.51622275 0.06293298 0.82376726 0.43800594]

sorted:
[0.06293298 0.43800594 0.51622275 0.64587158 0.82376726 0.83632996]


## Iterators

Often times you want to iterate over an array. Two common patterns are using an index variable and using iterators. I suggest using iterators when you can because they are less error prone and more idiomatic python.

In [ ]:
vector = np.arange(5)
print('starting data:')
print(vector)
print()

# using an iterator
for element in vector:
  element **= 2
  print(element)

print('notice this didnt mutate our vector: ')
print(vector)
print()

# you decide which is better...
for i in range(len(vector)):
  vector[i] **= 2
  print(vector[i])

print('but this one did mutate it: ')
print(vector)
print('This is because python avoids mutation through iterators for optimization')

starting data:
[0 1 2 3 4]

0
1
4
9
16
notice this didnt mutate our vector: 
[0 1 2 3 4]

0
1
4
9
16
but this one did mutate it: 
[ 0  1  4  9 16]
This is because python avoids mutation through iterators for optimization


## Exercise 1

For the first section of in class exercises to prepare you for the first homework, do the following:

### Level 1
*   Create a numpy vector with the row sums of $A$
*   Create a numpy vector with the column sums of $A$
*   Find the average of the elements of $A$

### Level 2
*   Calculate $A^{10000} v$ using a loop. Think about the most efficient way to do this...
*   Calculate $A  A^T$. Check with a loop if the matrix is symmetric
*   Calculate $||v||_{l_2}$ by hand. Check if it is correct with `np.linalg.norm(v)`

### Level 3
*   Calculate $Av$ by hand and check it is correct with `A @ v` or `A.dot(v)`
*   Calculate $vv^T$ by hand and check if it is correct with `v @ v.T`
*   Using the result from the previous step, calculate $A - vv^T$ and check with `A - v @ v.T`

In [ ]:
import numpy as np

A = np.random.rand(3, 3)
v = np.random.rand(3, 1)

################
#    Level 1   #
################
print(A)
print()
#1_a
#The sow sums of A
sum_row = np.sum(A, axis = 1)
print("The row sums of A")
print(sum_row)
print()

#1_b
#The column sums of A
sum_col = np.sum(A, axis = 0)
print("The column sum of A")
print(sum_col)
print()

#1_c
#The row averages of A
ave_row = np.average(A, axis = 1)
print("The row average of A")
print(ave_row)
print()

#The column averages of A
ave_col = np.average(A, axis = 0)
print("The column average of A")
print(ave_col)
print()


[[0.55732643 0.46296255 0.07335815]
 [0.59262604 0.97636018 0.25783119]
 [0.06199761 0.82845852 0.61706769]]

The row sums of A
[1.09364713 1.8268174  1.50752382]

The column sum of A
[1.21195008 2.26778125 0.94825703]

The row average of A
[0.36454904 0.60893913 0.50250794]

The column average of A
[0.40398336 0.75592708 0.31608568]



In [ ]:
################
#    Level 2   #
################
#2_a
print(A, "\n")
print(v, "\n")

A_expo = A @ A
print(A_expo, "\n")

n = 1
ans = A
while n < 100:
  ans = ans @ A
  n += 1

print(ans, "\n") 

#when n equals to 10000, the matrix is too large
#change 10000 to 100
A_time_v = A @ v
print("Matrix A times Vector v is:\n",A_time_v, "\n")

##test1 = A @ A @ A
##print(test1)
#2_b
#A transpose
A_transp = A.transpose()
print("transpose A is:")
print(A_transp, "\n")

A_time_AT = A @ A_transp
print("A times A transpose is:\n", A_time_AT, "\n")

#2_c
Frob_norm = np.linalg.norm(v)
print("the Frobenius norm is:\n", Frob_norm, "\n")



[[0.55732643 0.46296255 0.07335815]
 [0.59262604 0.97636018 0.25783119]
 [0.06199761 0.82845852 0.61706769]] 

[[0.08824686]
 [0.79408155]
 [0.83482162]] 

[[0.58952444 0.77081365 0.20551756]
 [0.92488753 1.4412453  0.45430935]
 [0.56377572 1.34879147 0.59892301]] 

[[1.05997803e+18 1.69662028e+18 5.59071861e+17]
 [1.95664143e+18 3.13183619e+18 1.03200551e+18]
 [1.83034564e+18 2.92968482e+18 9.65392408e+17]] 

Matrix A times Vector v is:
 [[0.47805329]
 [1.04285003]
 [1.17847617]] 

transpose A is:
[[0.55732643 0.59262604 0.06199761]
 [0.46296255 0.97636018 0.82845852]
 [0.07335815 0.25783119 0.61706769]] 

A times A transpose is:
 [[0.53032849 0.80121837 0.46336512]
 [0.80121837 1.37096173 1.0047146 ]
 [0.46336512 1.0047146  1.07095977]] 

the Frobenius norm is:
 1.1555432295983126 



In [ ]:
################
#    Level 3   #
################




## Homework 1

For the first homework you will implement $LU$ factorization and use the factorization to solve a two part linear system using the triangular matrices.

You will solve for $Ax = \mathbb{1}$. Once you have $A = LU$ you can solve the problem by doing:
*   First find $v$ with lower triangular solve: $Lv = \mathbb{1}$ 
*   Then find $x$ with upper triangular solve: $Ux = v$

Note: plugging $v = Ux$ into $Lv = \mathbb{1}$ gives $LUx = \mathbb{1}$ or $Ax = \mathbb{1}$.

Work with either `100_orthonormal.npy` or `1000_orthonormal.npy`.

You can check your work by using `np.solve(A, b)` and finding the norm of the difference with your solution.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
folder = 'drive/MyDrive/MTH343/matrices'


Mounted at /content/drive


In [ ]:
import numpy as np

A = np.load(f'{folder}/100_orthonormal.npy')
b = np.ones(100)

# guessing random numbers probably wont work but let's try
# (your code goes here)
x = np.random.rand(100)

# Check your work:
actual_solution = np.linalg.solve(A, b)
print(f'norm of error: {np.linalg.norm(x - actual_solution)}')

norm of error: 11.919476655724383


In [ ]:
print(A)

[[-0.07047942 -0.03473162 -0.17349873 ...  0.1606415   0.31964962
  -0.18321195]
 [-0.12518212 -0.03546028  0.07271342 ...  0.11974919 -0.22927868
  -0.05191987]
 [-0.00077188 -0.18132404  0.01457022 ... -0.04190269  0.0805136
  -0.03097356]
 ...
 [-0.12567548  0.01144142  0.08755717 ...  0.06764805 -0.11347368
   0.03149286]
 [-0.14326392  0.09813543 -0.06890171 ... -0.14358401 -0.07232055
  -0.06155001]
 [-0.15506036  0.09034761  0.12193978 ... -0.04932714  0.07339221
  -0.08073681]]


In [ ]:
def lu(Mat):
    n = Mat.shape[0]
    U = np.zeros((n, n), dtype=np.double)
    L = np.eye(n, dtype=np.double)
    for k in range(n):
        U[k, k:] = Mat[k, k:] - L[k,:k] @ U[:k,k:]
        L[(k+1):,k] = (Mat[(k+1):,k] - L[(k+1):,:] @ U[:,k]) / U[k, k]
    return L, U

In [ ]:
L, U = lu(A)
print(L)

[[ 1.          0.          0.         ...  0.          0.
   0.        ]
 [ 1.77615147  1.          0.         ...  0.          0.
   0.        ]
 [ 0.01095185 -6.89878543  1.         ...  0.          0.
   0.        ]
 ...
 [ 1.78315161  2.79747665 -0.2528533  ...  1.          0.
   0.        ]
 [ 2.03270587  6.43329375 -0.81939194 ... -0.66145477  1.
   0.        ]
 [ 2.20008017  6.35800719 -0.72538584 ...  0.89433064 -0.76235374
   1.        ]]


In [ ]:
print(U)

[[ -0.07047942  -0.03473162  -0.17349873 ...   0.1606415    0.31964962
   -0.18321195]
 [  0.           0.02622834   0.38087343 ...  -0.16557444  -0.79702481
    0.27349231]
 [  0.           0.           2.64403445 ...  -1.18592455  -5.42149033
    1.8577977 ]
 ...
 [  0.           0.           0.         ...   8.43827662  -6.97180116
  -11.4930459 ]
 [  0.           0.           0.         ...   0.          -7.79597143
   -7.08677418]
 [  0.           0.           0.         ...   0.           0.
  -12.3859234 ]]


In [ ]:
np.allclose(A, L @ U)

True

In [ ]:
#Lv = b
def Lv_b(L, b):
  #number of row
  n = L.shape[0]
  #return an array of zeroos with the same shape
  v = np.zeros_like(b, dtype = np.double)

  #calculate Lv = b, so v = b / L
  #first row is v[1] = b[1] / L[1, 1]
  #second row is v[2] = (b[2] - L[2, 1] * y[1]]) / L[2, 2]
  # ....
  v[0] = b[0] / L[0, 0]

  for i in range(1, n):
    v[i] = (b[i] - np.dot(L[i, :i], v[:i])) / L[i, i]
  return v

print("The matrix v is: \n", Lv_b(L, b))



The matrix v is: 
 [ 1.         -0.77615147 -4.36545431 -0.41664068 -0.50537318  3.26338663
  0.50161626  0.65737473 10.70672953 -1.94913472 -0.45196261  1.1590193
 -0.9300986  -2.25115348 -1.85769575  1.39035377  0.67315012 -0.54821749
  0.72467929  0.02329838 -0.29351706 -0.01961737 -0.1170711  -1.49623396
 -0.25202855 -1.62148444 -0.44884606  0.91126919 -1.29025068  1.03785036
 -1.56622102  0.55914055  1.4472684   1.17179886 -0.51234302  2.82554295
 -4.65342993 -1.49757537 -0.45241714 -4.98006395 -1.38335201  0.77081386
 -0.0182535  -0.60589869 -1.17146524 -0.92641286  0.99868551  0.77614558
 -1.94021867 -0.84816066  2.13682002  0.39297051  0.08610391  0.22882843
 -0.76477997 -0.16007001  7.54656847 -1.25898306 -0.66464111  2.51807122
 -0.29979398 -1.11933797  0.81096735  0.40923238 -0.05295054  0.17918599
  1.13524485 -3.75313914 -1.28481345 -0.95939835 -3.12209028  0.95698592
  4.54186611 -0.97914481  2.2234579  -1.36366072  1.19425038 -0.73392984
 -1.50080262  0.17226396  0.66609

In [ ]:
#v = Ux
def v_Ux(U, v):
  #Number of row
  n = U.shape[0]
  #return an array of zeroos with the same shape
  x = np.zeros_like(b, dtype = np.double)

  #calculate v = Ux, so x = v / U
  #first row is  x[n] = v[n] / U[n, n]
  #second row is x[n-1] = (v[n-1] - U[n-1, n] * x[n]) / U[n-1, n-1]
  x[-1] = v[-1] / U[-1, -1]

  for i in range(n-2, -1, -1):
    x[i] = (v[i] - np.dot(U[i, i:], x[i:])) / U[i,i]
  return x

v_Ux(U, Lv_b(L, b))

array([-8.59573153e+00, -3.77342677e+00, -1.66480285e+00,  1.47284907e+00,
        1.15210220e+00,  8.63708265e-01, -7.84324967e-01,  7.00091143e-01,
       -6.50049780e-01,  8.63250476e-01, -3.69931611e-01, -5.42305361e-01,
        2.95643716e-01, -3.89308992e-01,  5.47002141e-01,  1.98709520e-01,
        1.44682331e-01, -1.79879744e-01,  2.84065872e-01,  2.08572362e-01,
        4.98118984e-02, -3.74259574e-01,  2.61354106e-01, -2.85109596e-01,
        1.48895894e-01, -1.13402685e-01,  1.24892432e-01, -1.97067423e-01,
       -2.26982867e-01, -3.42244779e-01,  2.40739410e-01, -2.49270749e-01,
       -8.75702945e-02, -2.60952865e-01,  2.66234920e-01,  8.71319636e-02,
        7.88312463e-02,  2.10339023e-01, -1.20030568e-01,  1.03311973e-01,
        1.37696780e-01, -4.33348613e-02,  1.18412215e-01,  1.40229378e-01,
        1.35079408e-01, -2.54847696e-01, -8.93976125e-02, -2.31502576e-03,
       -9.04843482e-03,  7.04232244e-02, -1.51828932e-01,  3.73615225e-02,
       -1.01334904e-01,  

In [ ]:
A @ v_Ux(U, Lv_b(L, b))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])